.TH "QDevelop" "1" "Feb 09, 2008" "" ""
.SH "NAME"
QDevelop \- A development environment entirely dedicated to Qt4
.SH "SYNOPSIS"
.B qdevelop
.B \-l
.I [Language]
.I [file(s)]
.I [project.pro]
.SH "DESCRIPTION"
This manual page documents briefly the
.B QDevelop
commands.
.PP 
\fBQDevelop\fP is a development environment entirely dedicated to Qt4.
 It consists of a Qt project manager, a source code editor, build\-automation tools by calling make command, and the gdb debugger.

 QDevelop aims to be easy to use and does not try to compete with more complete tools, like KDevelop, which are often too complex. Its goal is simplicity, powerfulness and a same interface on all platforms.

.SH "OPTIONS"
.TP 
.B \-l [Language]
Force QDevelop to use Language instead of the system language.
Available languages are English, French, German and Dutch
.SH "SEE ALSO"
.BR ctags (1),
.BR gdb (1).
.br 
.SH "AUTHOR"
QDevelop was written by Jean\-Luc Biord <jl.biord@free.fr>.
.PP 
This manual page was written by Daniel Rocher <daniel.rocher@adella.org>
and modified by Guillaume Martres <smarter@ubuntu.com> for the Debian project (but may be used by others).
